/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clases;

import java.awt.Color;
import java.awt.Graphics;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Ingeniero Alexander Gonzalez.
 */
public class GraficaMarcas extends javax.swing.JFrame {

    int acer, alienware, apple, asus, brother, dell, hp, janus, lenovo, samsung, toshiba, xerox, otra;
    int totalMarcas = 0;
    String marca;
    boolean bandera = true;
    int contador1, contador2, contador3, contador4, contador5;
    
    
    public GraficaMarcas() {
        this.setIconImage(new ImageIcon(getClass().getResource("/img/Tecnico.jpg")).getImage());
        this.setTitle(Login.tipoUser + " - Sesion de " + Login.username);
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        
        
    }

    
    public void datosConsultados(String tipoUser, String nombreUser) {
    try {
            Conexion conex = new Conexion();
            conex.conexionBd();
            PreparedStatement pst = conex.conexionBd().prepareStatement("SELECT marca from equipos" );
            
            ResultSet rs = pst.executeQuery();
         
          
                while(rs.next()){
                marca = rs.getString("marca"); 
             
           if(marca.equals("Acer"))
               acer++;
               
            else if(marca.equals("Apple"))
                apple++;
            else if (marca.equals("Asus"))
                asus++;
            else if (marca.equals("Alienware"))
                alienware++;
            else if (marca.equals("Brother"))
                brother++;
            else if (marca.equals("Dell"))
                dell++;
            else if (marca.equals("Hp"))
                hp++;
            else if (marca.equals("Janus"))
                janus++;
            else if (marca.equals("Lenovo"))
                lenovo++;
            else if (marca.equals("Samsung"))
                samsung++;
            else if (marca.equals("Toshiba"))
                toshiba++;
            else if (marca.equals("Xerox"))
                xerox++;
            else
                otra++;    
                      
            }
            
            conex.conexionBd().close();
            rs.close();
            pst.getConnection().close();
            
            initComponents();
            this.setLocationRelativeTo(null);
                    
        } catch (SQLException e) {
            System.out.println("ERROR en la conexion a la BD" + e);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("GRAFÍCA DE MARCAS");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel2.setText("Creado por Ing. Alexander Gonzalez G.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(jLabel2)))
                .addContainerGap(182, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 326, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GraficaMarcas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GraficaMarcas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GraficaMarcas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GraficaMarcas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GraficaMarcas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

    
    @Override
    public void paint(Graphics g){
            super.paint(g);
            
            totalMarcas = acer+alienware+apple+asus+brother+dell+hp+janus+lenovo+samsung+toshiba+xerox+otra;
            
            if(bandera == true && totalMarcas !=0){
                try{
                int grados_acer = acer * 360 / totalMarcas;
                int grados_alienware =  alienware * 360 / totalMarcas;
                int grados_apple = apple * 360 / totalMarcas;
                int grados_asus = asus * 360 / totalMarcas;
                int grados_brother = brother * 360 / totalMarcas;
                int grados_dell = dell * 360 / totalMarcas;
                int grados_hp = hp * 360 / totalMarcas;
                int grados_janus = janus * 360 / totalMarcas;
                int grados_lenovo = lenovo * 360 / totalMarcas;
                int grados_samsung = samsung * 360 / totalMarcas;
                int grados_toshiba = toshiba * 360 / totalMarcas;       
                int grados_xerox = xerox * 360 / totalMarcas;
                int grados_otra = otra * 360 / totalMarcas;
                
                
                
                g.setColor(new Color(255,0,0));
                g.fillArc(25, 80, 200, 200, 0,grados_acer);
                g.fillRect(250,80,20,20);
                g.drawString("Acer: " +acer, 275,95);

                g.setColor(new Color(0,60,0));
                g.fillArc(25, 80, 200, 200, grados_acer,grados_alienware);
                g.fillRect(375, 80, 20, 20);
                g.drawString("Alienware: "+alienware,400, 95);

                g.setColor(new Color(0,0,255));
                g.fillArc(25, 80, 200, 200, grados_acer + grados_alienware, grados_apple);
                g.fillRect(250, 110, 20, 20);
                g.drawString("Apple: "+apple, 275, 125);
                
                g.setColor(new Color(130,65,0));
                g.fillArc(25, 80, 200, 200, grados_acer + grados_alienware + grados_apple, grados_asus);
                g.fillRect(375, 110, 20, 20);
                g.drawString("Asus: "+asus, 400, 125);
                
                g.setColor(new Color(90,180,0));
                g.fillArc(25, 80, 200, 200, grados_acer + grados_alienware + grados_apple + grados_asus, grados_brother);
                g.fillRect(250, 140, 20, 20);
                g.drawString("Brother: "+brother, 275, 155);
                
                g.setColor(new Color(255,130,0));
                g.fillArc(25, 80, 200, 200, grados_acer + grados_alienware + grados_apple + grados_asus 
                          + grados_brother, grados_dell);
                g.fillRect(375, 140, 20, 20);
                g.drawString("Dell: "+dell, 400, 155);
                
                g.setColor(new Color(130,0,0));
                g.fillArc(25, 80, 200, 200, grados_acer + grados_alienware + grados_apple + grados_asus 
                          + grados_brother + grados_dell, grados_hp);
                g.fillRect(250, 170, 20, 20);
                g.drawString("Hp: "+hp, 275, 185);
                
                g.setColor(new Color(60,110,110));
                g.fillArc(25, 80, 200, 200, grados_acer + grados_alienware + grados_apple + grados_asus 
                          + grados_brother + grados_dell + grados_hp, grados_janus);
                g.fillRect(375, 170, 20, 20);
                g.drawString("Janus: "+janus, 400, 185);
                
                g.setColor(new Color(0,0,0));
                g.fillArc(25, 80, 200, 200, grados_acer + grados_alienware + grados_apple + grados_asus 
                          + grados_brother + grados_dell + grados_hp + grados_janus, grados_lenovo);
                g.fillRect(250, 200, 20, 20);
                g.drawString("Lenovo", 275, 215);
                
                g.setColor(new Color(65,65,65));
                g.fillArc(25, 80, 200, 200, grados_acer + grados_alienware + grados_apple + grados_asus 
                          + grados_brother + grados_dell + grados_hp + grados_janus + grados_lenovo, grados_samsung);
                g.fillRect(375, 200, 20, 20);
                g.drawString("Samsung: " +samsung, 400, 215);
                
                g.setColor(new Color(130,100,0));
                g.fillArc(25, 80, 200, 200, grados_acer + grados_alienware + grados_apple + grados_asus 
                          + grados_brother + grados_dell + grados_hp + grados_janus + grados_lenovo
                        + grados_samsung, grados_toshiba);
                g.fillRect(250, 230, 20, 20);
                g.drawString("Toshiba: "+toshiba, 275, 245);
                
                g.setColor(new Color(255,0,255));
                g.fillArc(25, 80, 200, 200, grados_acer + grados_alienware + grados_apple + grados_asus 
                          + grados_brother + grados_dell + grados_hp + grados_janus + grados_lenovo
                        + grados_samsung + grados_toshiba, grados_xerox);
                g.fillRect(375, 230, 20, 20);
                g.drawString("Xerox: "+xerox, 400, 245);
                
                g.setColor(new Color(0,130,190));
                g.fillArc(25, 80, 200, 200, grados_acer + grados_alienware + grados_apple + grados_asus 
                          + grados_brother + grados_dell + grados_hp + grados_janus + grados_lenovo
                        + grados_samsung + grados_toshiba + grados_xerox, grados_otra);
                g.fillRect(250, 260, 20, 20);
                g.drawString("Otras: "+otra, 275, 275);
                }catch(ArithmeticException ep){
                    ep.printStackTrace();
                }
                
                } else {
                    JOptionPane.showMessageDialog(null, "No hay Equipos Registrados");
                }
            
        }


}
